/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: bd048fe4903b9908bde77ea8b881dea1)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "PlantCare";
	}
	interface Env {
		PlantCare: DurableObjectNamespace<import("./src/server").PlantCare>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
